/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppVisitsRouteImport } from './routes/_authenticated/app/visits'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppTerritoriesRouteImport } from './routes/_authenticated/app/territories'
import { Route as AuthenticatedAppStoresRouteImport } from './routes/_authenticated/app/stores'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppFormsRouteImport } from './routes/_authenticated/app/forms'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app/campaigns'
import { Route as AuthenticatedAppStoresStoreIdRouteImport } from './routes/_authenticated/app/stores.$storeId'
import { Route as AuthenticatedAppStoresStoreIdTimelineRouteImport } from './routes/_authenticated/app/stores.$storeId.timeline'
import { Route as AuthenticatedAppFormsFormIdResponsesRouteImport } from './routes/_authenticated/app/forms.$formId.responses'
import { Route as AuthenticatedAppVisitsCampaignIdStoreIdFormIdRouteImport } from './routes/_authenticated/app/visits.$campaignId.$storeId.$formId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVisitsRoute = AuthenticatedAppVisitsRouteImport.update({
  id: '/app/visits',
  path: '/app/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/app/users',
  path: '/app/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTerritoriesRoute =
  AuthenticatedAppTerritoriesRouteImport.update({
    id: '/app/territories',
    path: '/app/territories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppStoresRoute = AuthenticatedAppStoresRouteImport.update({
  id: '/app/stores',
  path: '/app/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/app/products',
    path: '/app/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFormsRoute = AuthenticatedAppFormsRouteImport.update({
  id: '/app/forms',
  path: '/app/forms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/app/campaigns',
    path: '/app/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppStoresStoreIdRoute =
  AuthenticatedAppStoresStoreIdRouteImport.update({
    id: '/$storeId',
    path: '/$storeId',
    getParentRoute: () => AuthenticatedAppStoresRoute,
  } as any)
const AuthenticatedAppStoresStoreIdTimelineRoute =
  AuthenticatedAppStoresStoreIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedAppStoresStoreIdRoute,
  } as any)
const AuthenticatedAppFormsFormIdResponsesRoute =
  AuthenticatedAppFormsFormIdResponsesRouteImport.update({
    id: '/$formId/responses',
    path: '/$formId/responses',
    getParentRoute: () => AuthenticatedAppFormsRoute,
  } as any)
const AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute =
  AuthenticatedAppVisitsCampaignIdStoreIdFormIdRouteImport.update({
    id: '/$campaignId/$storeId/$formId',
    path: '/$campaignId/$storeId/$formId',
    getParentRoute: () => AuthenticatedAppVisitsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/forms': typeof AuthenticatedAppFormsRouteWithChildren
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/stores': typeof AuthenticatedAppStoresRouteWithChildren
  '/app/territories': typeof AuthenticatedAppTerritoriesRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/visits': typeof AuthenticatedAppVisitsRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/stores/$storeId': typeof AuthenticatedAppStoresStoreIdRouteWithChildren
  '/app/forms/$formId/responses': typeof AuthenticatedAppFormsFormIdResponsesRoute
  '/app/stores/$storeId/timeline': typeof AuthenticatedAppStoresStoreIdTimelineRoute
  '/app/visits/$campaignId/$storeId/$formId': typeof AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/forms': typeof AuthenticatedAppFormsRouteWithChildren
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/stores': typeof AuthenticatedAppStoresRouteWithChildren
  '/app/territories': typeof AuthenticatedAppTerritoriesRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/visits': typeof AuthenticatedAppVisitsRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/stores/$storeId': typeof AuthenticatedAppStoresStoreIdRouteWithChildren
  '/app/forms/$formId/responses': typeof AuthenticatedAppFormsFormIdResponsesRoute
  '/app/stores/$storeId/timeline': typeof AuthenticatedAppStoresStoreIdTimelineRoute
  '/app/visits/$campaignId/$storeId/$formId': typeof AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/forms': typeof AuthenticatedAppFormsRouteWithChildren
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/stores': typeof AuthenticatedAppStoresRouteWithChildren
  '/_authenticated/app/territories': typeof AuthenticatedAppTerritoriesRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/app/visits': typeof AuthenticatedAppVisitsRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/stores/$storeId': typeof AuthenticatedAppStoresStoreIdRouteWithChildren
  '/_authenticated/app/forms/$formId/responses': typeof AuthenticatedAppFormsFormIdResponsesRoute
  '/_authenticated/app/stores/$storeId/timeline': typeof AuthenticatedAppStoresStoreIdTimelineRoute
  '/_authenticated/app/visits/$campaignId/$storeId/$formId': typeof AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/campaigns'
    | '/app/forms'
    | '/app/products'
    | '/app/stores'
    | '/app/territories'
    | '/app/users'
    | '/app/visits'
    | '/app/'
    | '/app/stores/$storeId'
    | '/app/forms/$formId/responses'
    | '/app/stores/$storeId/timeline'
    | '/app/visits/$campaignId/$storeId/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/campaigns'
    | '/app/forms'
    | '/app/products'
    | '/app/stores'
    | '/app/territories'
    | '/app/users'
    | '/app/visits'
    | '/app'
    | '/app/stores/$storeId'
    | '/app/forms/$formId/responses'
    | '/app/stores/$storeId/timeline'
    | '/app/visits/$campaignId/$storeId/$formId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/forms'
    | '/_authenticated/app/products'
    | '/_authenticated/app/stores'
    | '/_authenticated/app/territories'
    | '/_authenticated/app/users'
    | '/_authenticated/app/visits'
    | '/_authenticated/app/'
    | '/_authenticated/app/stores/$storeId'
    | '/_authenticated/app/forms/$formId/responses'
    | '/_authenticated/app/stores/$storeId/timeline'
    | '/_authenticated/app/visits/$campaignId/$storeId/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/visits': {
      id: '/_authenticated/app/visits'
      path: '/app/visits'
      fullPath: '/app/visits'
      preLoaderRoute: typeof AuthenticatedAppVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/app/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/territories': {
      id: '/_authenticated/app/territories'
      path: '/app/territories'
      fullPath: '/app/territories'
      preLoaderRoute: typeof AuthenticatedAppTerritoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/stores': {
      id: '/_authenticated/app/stores'
      path: '/app/stores'
      fullPath: '/app/stores'
      preLoaderRoute: typeof AuthenticatedAppStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/app/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/forms': {
      id: '/_authenticated/app/forms'
      path: '/app/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AuthenticatedAppFormsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/app/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/stores/$storeId': {
      id: '/_authenticated/app/stores/$storeId'
      path: '/$storeId'
      fullPath: '/app/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedAppStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedAppStoresRoute
    }
    '/_authenticated/app/stores/$storeId/timeline': {
      id: '/_authenticated/app/stores/$storeId/timeline'
      path: '/timeline'
      fullPath: '/app/stores/$storeId/timeline'
      preLoaderRoute: typeof AuthenticatedAppStoresStoreIdTimelineRouteImport
      parentRoute: typeof AuthenticatedAppStoresStoreIdRoute
    }
    '/_authenticated/app/forms/$formId/responses': {
      id: '/_authenticated/app/forms/$formId/responses'
      path: '/$formId/responses'
      fullPath: '/app/forms/$formId/responses'
      preLoaderRoute: typeof AuthenticatedAppFormsFormIdResponsesRouteImport
      parentRoute: typeof AuthenticatedAppFormsRoute
    }
    '/_authenticated/app/visits/$campaignId/$storeId/$formId': {
      id: '/_authenticated/app/visits/$campaignId/$storeId/$formId'
      path: '/$campaignId/$storeId/$formId'
      fullPath: '/app/visits/$campaignId/$storeId/$formId'
      preLoaderRoute: typeof AuthenticatedAppVisitsCampaignIdStoreIdFormIdRouteImport
      parentRoute: typeof AuthenticatedAppVisitsRoute
    }
  }
}

interface AuthenticatedAppFormsRouteChildren {
  AuthenticatedAppFormsFormIdResponsesRoute: typeof AuthenticatedAppFormsFormIdResponsesRoute
}

const AuthenticatedAppFormsRouteChildren: AuthenticatedAppFormsRouteChildren = {
  AuthenticatedAppFormsFormIdResponsesRoute:
    AuthenticatedAppFormsFormIdResponsesRoute,
}

const AuthenticatedAppFormsRouteWithChildren =
  AuthenticatedAppFormsRoute._addFileChildren(
    AuthenticatedAppFormsRouteChildren,
  )

interface AuthenticatedAppStoresStoreIdRouteChildren {
  AuthenticatedAppStoresStoreIdTimelineRoute: typeof AuthenticatedAppStoresStoreIdTimelineRoute
}

const AuthenticatedAppStoresStoreIdRouteChildren: AuthenticatedAppStoresStoreIdRouteChildren =
  {
    AuthenticatedAppStoresStoreIdTimelineRoute:
      AuthenticatedAppStoresStoreIdTimelineRoute,
  }

const AuthenticatedAppStoresStoreIdRouteWithChildren =
  AuthenticatedAppStoresStoreIdRoute._addFileChildren(
    AuthenticatedAppStoresStoreIdRouteChildren,
  )

interface AuthenticatedAppStoresRouteChildren {
  AuthenticatedAppStoresStoreIdRoute: typeof AuthenticatedAppStoresStoreIdRouteWithChildren
}

const AuthenticatedAppStoresRouteChildren: AuthenticatedAppStoresRouteChildren =
  {
    AuthenticatedAppStoresStoreIdRoute:
      AuthenticatedAppStoresStoreIdRouteWithChildren,
  }

const AuthenticatedAppStoresRouteWithChildren =
  AuthenticatedAppStoresRoute._addFileChildren(
    AuthenticatedAppStoresRouteChildren,
  )

interface AuthenticatedAppVisitsRouteChildren {
  AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute: typeof AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute
}

const AuthenticatedAppVisitsRouteChildren: AuthenticatedAppVisitsRouteChildren =
  {
    AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute:
      AuthenticatedAppVisitsCampaignIdStoreIdFormIdRoute,
  }

const AuthenticatedAppVisitsRouteWithChildren =
  AuthenticatedAppVisitsRoute._addFileChildren(
    AuthenticatedAppVisitsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppFormsRoute: typeof AuthenticatedAppFormsRouteWithChildren
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppStoresRoute: typeof AuthenticatedAppStoresRouteWithChildren
  AuthenticatedAppTerritoriesRoute: typeof AuthenticatedAppTerritoriesRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppVisitsRoute: typeof AuthenticatedAppVisitsRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppFormsRoute: AuthenticatedAppFormsRouteWithChildren,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppStoresRoute: AuthenticatedAppStoresRouteWithChildren,
  AuthenticatedAppTerritoriesRoute: AuthenticatedAppTerritoriesRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppVisitsRoute: AuthenticatedAppVisitsRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
